language: c
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.5"
    - LIBRARY_NAME="MCP23017"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_IDE_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
 - ln -s $PWD /usr/local/share/arduino/libraries/$LIBRARY_NAME
script:
 - arduino --verify --board arduino:avr:uno $PWD/examples/PortCopyOnInterrupt/PortCopyOnInterrupt.ino
 - arduino --verify --board arduino:avr:uno $PWD/examples/RegistersDumper/RegistersDumper.ino
notifications:
  email:
    on_success: change
    on_failure: change